version: '3.4'

services:
  mongodb:
    image: "mongo:latest"
    restart: always
    volumes:
      - saleproject_v:/etc/mongo
    ports:
      - 27018:27017
  saleproject:
    container_name: saleproject
    image: saleproject
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    environment:
      NODE_ENV: production
      MONGODB_URL: mongodb://mongodb:27017/saleproject
    ports:
      - 8080:8080
    depends_on:
      - mongodb
volumes:
  saleproject_v:
